#!/usr/bin/env python

from template_rospy_pkg.template_node import TemplateNode
from template_rospy_pkg.utils.config_util import *


if __name__ == '__main__':
    ros_args, user_args = parse_args()
    TemplateNode(ros_args["__name"])

